#!/bin/bash

mpv --no-video ~/.pixelfiles/sounds-pixelfiles/menu1.mp3 &

declare -a options=(
  "Shutdown"
  "Reboot"
  "Lock"
  "Exit DWM"
  "Close"
)

choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l 15 -p 'Shutdown menu:' "${@}")

case $choice in
  "Lock") slock ;;

  "Exit DWM") 
    mpv --no-video ~/.pixelfiles/sounds-pixelfiles/menu2.mp3 &
    if [[ "$(echo -e "No\nYes" | dmenu -i -l 15 -p "Do you want to ${choice}?" "${@}" )" == "Yes" ]]; then
      brightnessctl s 0%
      mpv --no-video ~/.pixelfiles/sounds-pixelfiles/poweroff.mp3
      killall dwm
    else
      echo "Hmmm :\ " >> /dev/null
    fi
  ;;

  "Reboot")
    mpv --no-video ~/.pixelfiles/sounds-pixelfiles/menu2.mp3 &
    if [[ "$(echo -e "No\nYes" | dmenu -i -l 15 -p "Do you want to ${choice}?" "${@}" )" == "Yes" ]]; then
      brightnessctl s 0%
      mpv --no-video ~/.pixelfiles/sounds-pixelfiles/poweroff.mp3
      systemctl reboot
    else
      echo "Hmmm :\ " >> /dev/null
    fi
  ;;

  "Shutdown")
    mpv --no-video ~/.pixelfiles/sounds-pixelfiles/menu2.mp3 &
    if [[ "$(echo -e "No\nYes" | dmenu -i -l 15 -p "Do you want to ${choice}?" )" == "Yes" ]]; then
      brightnessctl s 0%
      mpv --no-video ~/.pixelfiles/sounds-pixelfiles/poweroff.mp3
      poweroff
    else
      echo "Hmmm :\ " >> /dev/null
    fi
  ;;

  "Close") echo "Hmmm :\ " >> /dev/null;;
esac

